name: ci

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 13
     
    - name: Start server
      run: |
          npm run build
          npm run start &

    - name: Wait for server to start
      run: |
          while ! curl -s http://localhost:3000 > /dev/null; do
            sleep 1
          done

    - name: Keep server running
      run: |
          tail -f /dev/null

   
